debug generate failed Test SCript

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -279,7 +279,24 @@ jobs:
                     --tox-env ${{ matrix.tox_env }} \
                     --prefix failed
                 fi
-            
+          
+                
+      - name: Debug Generated Failed Test Script
+        shell: bash
+        run: |
+                  SCRIPT_PATH="artifacts/pr-${PR_ID}/${WORKFLOW_ID}/run_failed_tests_failed.sh"
+                  echo "Looking for script at: $SCRIPT_PATH"
+              
+                  if [[ -f "$SCRIPT_PATH" ]]; then
+                    echo "Script exists. Showing contents:"
+                    cat "$SCRIPT_PATH"
+                  else
+                    echo "Script not found!"
+                    ls -R artifacts/pr-${PR_ID}/${WORKFLOW_ID} || echo "Directory missing"
+                  fi
+
+
+          
       - name: Run Previously Failed Tests First
         shell: bash
         run: |
